### ISSUE TITLE
Not able to receive incoming fax.

### ISSUE THREAD

**Issue by swaroopkatargunde** [ictinnovations/ictfax#10]
Hi Team 

Need help for incoming fax to work. 

I have assigned a did to one user. and also white listed the domain from their the fax were going to come.

But when troubleshooting ,below are the errror which i am getting 

U 115.114.207.243:5060 -> 10.7.2.170:5060
  INVITE sip:16312301470@10.7.2.170:5060 SIP/2.0..Via: SIP/2.0/UDP 115.114.207.243:5060;branch=z9hG4bK08B1149e637ca9646a5..From: <sip:16132493700@115.114.207.243>;tag=gK0803295a..To: <sip:16312301470@10.7.2.170>..Call-ID: 1162386098_1
  21087914@115.114.207.243..CSeq: 926779 INVITE..Max-Forwards: 70..Allow: INVITE,ACK,CANCEL,BYE,REGISTER,REFER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS,MESSAGE,PUBLISH..Accept: application/sdp, application/isup, application/dtmf, ap
  plication/dtmf-relay, multipart/mixed..Contact: <sip:16132493700@115.114.207.243:5060>..P-Preferred-Identity: <sip:16132493700@115.114.207.243:5060>..Supported: timer,100rel,precondition,replaces..Session-Expires: 1800..Min-SE: 90..
  Content-Length:   268..Content-Disposition: session; handling=required..Content-Type: application/sdp....v=0..o=Sonus_UAC 495835 414182 IN IP4 115.114.207.243..s=SIP Media Capabilities..c=IN IP4 115.114.207.242..t=0 0..m=audio 16608
   RTP/AVP 0 8 101..a=rtpmap:0 PCMU/8000..a=rtpmap:8 PCMA/8000..a=rtpmap:101 telephone-event/8000..a=fmtp:101 0-15..a=sendrecv..a=maxptime:20..

U 10.7.2.170:5060 -> 115.114.207.243:5060
  SIP/2.0 100 Trying..Via: SIP/2.0/UDP 115.114.207.243:5060;branch=z9hG4bK08B1149e637ca9646a5..From: <sip:16132493700@115.114.207.243>;tag=gK0803295a..To: <sip:16312301470@10.7.2.170>..Call-ID: 1162386098_121087914@115.114.207.243..CS
  eq: 926779 INVITE..User-Agent: FreeSWITCH-mod_sofia/1.4.26~64bit..Content-Length: 0....

U 10.7.2.170:5060 -> 115.114.207.243:5060
  SIP/2.0 480 Temporarily Unavailable..Via: SIP/2.0/UDP 115.114.207.243:5060;branch=z9hG4bK08B1149e637ca9646a5..Max-Forwards: 70..From: <sip:16132493700@115.114.207.243>;tag=gK0803295a..To: <sip:16312301470@10.7.2.170>;tag=6rSQ6gDQj61
  5g..Call-ID: 1162386098_121087914@115.114.207.243..CSeq: 926779 INVITE..User-Agent: FreeSWITCH-mod_sofia/1.4.26~64bit..Accept: application/sdp..Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
  , PUBLISH, SUBSCRIBE..Supported: timer, path, replaces..Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer..Reaso
  n: Q.850;cause=16;text="NORMAL_CLEARING"..Content-Length: 0..P-Asserted-Identity: "16312301470" <sip:16312301470@10.7.2.170>....

U 115.114.207.243:5060 -> 10.7.2.170:5060
  ACK sip:16312301470@10.7.2.170:5060 SIP/2.0..Via: SIP/2.0/UDP 115.114.207.243:5060;branch=z9hG4bK08B1149e637ca9646a5..From: <sip:16132493700@115.114.207.243>;tag=gK0803295a..To: <sip:16312301470@10.7.2.170>;tag=6rSQ6gDQj615g..Call-I
  D: 1162386098_121087914@115.114.207.243..CSeq: 926779 ACK..Max-Forwards: 70..Content-Length: 0....

U 115.114.207.243:5060 -> 10.7.2.170:5060
  INVITE sip:16312301470@10.7.2.170:5060 SIP/2.0..Via: SIP/2.0/UDP 115.114.207.243:5060;branch=z9hG4bK04B04dd1659b3d54c88..From: <sip:16132493700@115.114.207.243>;tag=gK045d5579..To: <sip:16312301470@10.7.2.170>..Call-ID: 1160001556_3
  1448670@115.114.207.243..CSeq: 966742 INVITE..Max-Forwards: 70..Allow: INVITE,ACK,CANCEL,BYE,REGISTER,REFER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS,MESSAGE,PUBLISH..Accept: application/sdp, application/isup, application/dtmf, app
  lication/dtmf-relay, multipart/mixed..Contact: <sip:16132493700@115.114.207.243:5060>..P-Preferred-Identity: <sip:16132493700@115.114.207.243:5060>..Supported: timer,100rel,precondition,replaces..Session-Expires: 1800..Min-SE: 90..C
  ontent-Length:   268..Content-Disposition: session; handling=required..Content-Type: application/sdp....v=0..o=Sonus_UAC 570627 324425 IN IP4 115.114.207.243..s=SIP Media Capabilities..c=IN IP4 115.114.207.241..t=0 0..m=audio 37704
  RTP/AVP 0 8 101..a=rtpmap:0 PCMU/8000..a=rtpmap:8 PCMA/8000..a=rtpmap:101 telephone-event/8000..a=fmtp:101 0-15..a=sendrecv..a=maxptime:20..

U 10.7.2.170:5060 -> 115.114.207.243:5060
  SIP/2.0 100 Trying..Via: SIP/2.0/UDP 115.114.207.243:5060;branch=z9hG4bK04B04dd1659b3d54c88..From: <sip:16132493700@115.114.207.243>;tag=gK045d5579..To: <sip:16312301470@10.7.2.170>..Call-ID: 1160001556_31448670@115.114.207.243..CSe
  q: 966742 INVITE..User-Agent: FreeSWITCH-mod_sofia/1.4.26~64bit..Content-Length: 0....

**Comment by tahiralmas** [comment]
Hi,

Your error log is incomplete, please use attachment option for error log.
