### ISSUE TITLE
Can we attach multiple Files

### ISSUE THREAD

**Issue by mudasar321** [ictinnovations/ictfax#13]
Hi, I've one more question. Can we attach multiple files to send faxes out. Right now if I attach 1 pdf file system send faxes but if I attach 2 or more pdf system does not process the request. Please advise.

**Comment by tahiralmas** [comment]
Hi

We just released new version ICTFax 4.0, which support multiple attachment from email to fax and multiple document from Web to Fax

Please update your installation.

Regards
