### ISSUE TITLE
yum install ictfax

### ISSUE THREAD

**Issue by MarcoFayat** [ictinnovations/ictfax#14]
Hello, 

With the new version of ICTFAX 4.0

When i try to type :
yum install ictfax 

i got 
Error downloading packages:
  ictcore-sms-0.8.4.4-release.el7.noarch: [Errno 256] No more mirrors to try.
  ictcore-voice-0.8.4.4-release.el7.noarch: [Errno 256] No more mirrors to try.

Yum clean all does nothing.
I don't think it's a cache problem, i can't download the GUI then so i can't access to "IP_SERVER/ictfax"

Thanks for helping,

Marco

**Comment by tahiralmas** [comment]
Issue has been fixed, please issue following command before reinstallation, it will clear your yum cache

    yum clean all
