### ISSUE TITLE
Can't log with the new user

### ISSUE THREAD

**Issue by MarcoFayat** [ictinnovations/ictfax#15]
Hello, 

I can finally access to the admin panel, then I create a user (from User management)
When i log out with the admin and try to log with the new user, the authentification page is always showing, i can't access to the fax page. 
It's weird because it's like the user can login but can't access to the menu, always stick in the authentification page.

Can you help me out ? Thank you for the job :)

Sincerely,

Marco

**Comment by tahiralmas** [comment]
There is bug, until we fix it. you can work around by adding / assigning `user role` to newly created user. it can be done by inserting a record in `user_role` table in `ictfax` database

Note: user `1` user role and `2` for admin role. you should also assign user role to admin

**Comment by MarcoFayat** [comment]
I have no experience in MySql :(
Can you help me doing this in command line till the issue is fixed ?

Info : 
![forum1](https://user-images.githubusercontent.com/47565846/52850318-76df5c00-3113-11e9-93ec-f9a99d9f0b03.PNG)

Thank you ! @tahiralmas 

Marco

**Comment by tahiralmas** [comment]
Hi

We have fixed the bug and updated related binary packages. please execute following command on your server

    yum update ictfax ictcore ictcore-fax ictcore-email

After upgrade you will find a new feature under user management which will allow you to select desired roles while editing / creating new users. Hope it will fix the issue.
