### ISSUE TITLE
entrys under admin section not change or delete

### ISSUE THREAD

**Issue by maxs99** [ictinnovations/ictfax#17]
hi,
i got the error in ictcore

2019-03-11 15:11:01] [15528] [WARNING] mysql_error() expects parameter 1 to be resource, boolean given in /usr/ictcore/core/lib/DB.php on line 28
[2019-03-11 15:11:01] [15528] [ERROR] Unable to connect database server error:
[2019-03-11 15:11:37] [15251] [WARNING] Session read found zero rows
[2019-03-11 15:12:14] [15265] [WARNING] Session write failed

and in httpd

[root@faxserver httpd]# tail -f error_log 
[Mon Mar 11 16:08:12.919126 2019] [:error] [pid 15252] [client 172.17.0.87:52230] PHP Warning:  error_log(/usr/ictcore/log/ictcore.log): failed to open stream: Permission denied in /usr/ictcore/core/lib/Corelog.php on line 87, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:12.919374 2019] [:error] [pid 15252] [client 172.17.0.87:52230] PHP Warning:  error_log(/usr/ictcore/log/ictcore.log): failed to open stream: Permission denied in /usr/ictcore/core/lib/Corelog.php on line 87, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:12.919435 2019] [:error] [pid 15252] [client 172.17.0.87:52230] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:48.045789 2019] [:error] [pid 15263] [client 172.17.0.87:52236] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:48.667217 2019] [:error] [pid 15264] [client 172.17.0.87:52238] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:49.209623 2019] [:error] [pid 15265] [client 172.17.0.87:52240] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:49.397635 2019] [:error] [pid 15266] [client 172.17.0.87:52242] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:49.576429 2019] [:error] [pid 15249] [client 172.17.0.87:52244] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:49.925601 2019] [:error] [pid 15250] [client 172.17.0.87:52246] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/
[Mon Mar 11 16:08:50.098923 2019] [:error] [pid 15248] [client 172.17.0.87:52248] PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 28, referer: http://172.17.0.15/ictfax/

max

**Comment by tahiralmas** [comment]
Please check /usr/ictcore/etc/ictcore.conf  or /etc/ictcore.conf
and make sure that credential under the db section are valid,

**Comment by maxs99** [comment]
/etc/ictcore.conf is symlink to /usr/ictcore/etc/ictcore.conf

**Comment by tahiralmas** [comment]
yes, Just check the values under `[db]` section and validate these information my issuing following command and shell

     mysql -uUSERNAME -pPASSWORD DATABASE

note: replace above captial values from ictcore.conf. above command should work if credential are valid and  you have installed properly. Otherwise please reinstall ICTFax on fresh CentOs 7
