### ISSUE TITLE
Error while adding / updating / deleting Provider

### ISSUE THREAD

**Issue by plochu** [ictinnovations/ictfax#20]
Hi Guys!
I wanted to try out your solution but i have some difficulties.
1) Installed fresh CentOS 7
2) Followed your guide: http://ictfax.org/content/ictfax-installation-guide (points 1, 2 and 3)
3) There were no problems during installation
4) I logged into ICTfax dashboard

And now. When I tried to add Provider / Trunk after filling all fields and clicking Submit I got screen with:
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
[TAKE ME HOME]".

Now. Funny thing is that Provider was added but when I will try to update settings I will get the same error screen - but changes will be stored.
The same thing will happen when I will try to delete Provider - I will have error screen but Provider will remain.

I'm sure that trunk is not registering, I can see it on my test VoIP platform.

Any idea what can cause this problem?

Regards,

**Comment by syadnom** [comment]
Identical issue.  I also get this error trying to send a fax.  I tried thinking maybe the trunk was up and that was just a UI bug.

**Comment by plochu** [comment]
>  I tried thinking maybe the trunk was up and that was just a UI bug.

I'm 100% sure that trunk is down :) I can see it on the "other end" of it.

**Comment by plochu** [comment]
Any help?

**Comment by BzerkSkemer** [comment]
Same, fresh install from script

**Comment by megaman5** [comment]
Missing this file it looks like
https://github.com/ictinnovations/ictcore/blob/master/core/Service/Voice.php

**Comment by megaman5** [comment]
Looks like it goes here:
/usr/ictcore/core/Service/Voice.php

**Comment by plochu** [comment]
Ok, I downloaded this file manually.
Error screen is gone but VoIP account is still not registering to provider. On the provider side I even don't see registration attempts.

So this is still not all.

**Comment by BzerkSkemer** [comment]
I am experiencing this too. No registration attempts.

Talk To You Soon,
Scott Graham
Talk To You Soon Pty Limited
+61283213601
+61408100506
—
________________________________

**Comment by megaman5** [comment]
I changed the name of my provider, it seems it only saves when the name is changed.

**Comment by plochu** [comment]
I have even added new provider. Still no effect.

**Comment by megaman5** [comment]
This has nothing to do with this bug, so we should keep on topic.  This bug is that a file is missing, causing this problem.

I suggest you restart and 
tail -f /var/log/freeswitch/freeswitch.log

**Comment by plochu** [comment]
To be 100% sure I have made restart of whole server.
Then:

```
[root@localhost ~]# tail -f /var/log/freeswitch/freeswitch.log

2019-06-03 12:44:58.590964 [INFO] switch_core.c:2436
FreeSWITCH Version 1.6.20~64bit ( 64bit)
FreeSWITCH Started
Max Sessions [1000]
Session Rate [30]
SQL [Enabled]
2019-06-03 12;44;58.590969 [CONSOLE] switch_core.c:2444
[This app Best viewed at 160x60 or more..]
```

**Comment by plochu** [comment]
Also I have used FreeSWITCH cli to get log (sip trace) and nothing is happening in there.

Second thing is that `/etc/freeswitch/sip_profiles/ictcore.xml` in section gateways (that is used to configure external VoIP accounts, trunks or gateways) tries to include configuration files from `/usr/ictcore/etc/freeswitch/sip_profiles/provider/*.xml` but the problem is that this directory is empty. As I understand it should contain XML files generated when Provider is added in ICTFax GUI.

**Comment by megaman5** [comment]
did you turn off selinux?
setenforce 0

maybe it could not write the file?

**Comment by plochu** [comment]
> did you turn off selinux? setenforce 0

That is the point!
I just did it and it worked. Provider XML was generated and I can see that it is registered to my VoIP platform.

Thank you @megaman5 !!!

BTW. I was 99,999% sure that I did `setenforce 0` during installation... so I checked - it is necessary to do this after every server restart if you want to change anything in configuration of providers.
In next days I will make new, fresh ITCFax installation to check if I'm right or I made to much mess on this instance trying to force it to work.

**Comment by megaman5** [comment]
To make it permanent, you need to edit /etc/selinux/config and change to
disabled.
If this is production, you should go through the effort to work out exactly
what permissions are required and re-enable this.

**Comment by BzerkSkemer** [comment]
setenforce 0 worked for me.
I paid for the installation script.

**Comment by rw180800** [comment]
same issue ... no errors on install.  SELinux is disabled, all files above look to be there etc.  No attempt to register.

**Comment by rw180800** [comment]
I take it back ... potentially doesnt like hostnames .
