### ISSUE TITLE
Freeswitch Error when connecting to fs_cli: fs_cli.c:1659 main() Error Connecting [Socket Connection Error]

### ISSUE THREAD

**Issue by herrep** [ictinnovations/ictfax#24]
In order to properly debug ICTFAX, I want to connect to freeswitch which has been installed according to the provided installation guide for ICTFAX.

However, when starting fs_cli to access the cli of freeswitch, I receive the following error message:

fs_cli.c:1659 main() Error Connecting [Socket Connection Error]

What needs to be configured in order to run the cli of freeswitch?

**Comment by plochu** [comment]
That means that Freeswitch hasn't started... What OS are you using? Please check running services.

**Comment by ICTKashif** [comment]
ICTFax tested on CentOS 7.X, Please restart freeswitch by following command

`service freeswitch restart
`
if not work then run "freeswitch -nc"

**Comment by herrep** [comment]
Please note that freeswitch is running as a daemon. In a separate issue, I already published contents of the freeswitch log file where it is clear to see that the freeswitch daemon is running. However, I would like to gain access to the CLI of freeswitch. But fs_cli cannot connect to the running freeswitch. My assumption is that the installation guide did not expect that a user simply installing ICTFAX will also run fs_cli. I assume that further configuration needs to be applied that fs_cli can connect.

**Comment by herrep** [comment]
I want to gain access to fs_cli so that I can better debug freeswitch, e.g. to change debug settings. My main problem is that ICTFAX cannot connect to my Asterisk-based FreePBX which should act as a SIP provider to ICTFAX. The freeswitch log file simply says that no registration is possible. I would like to produce a log file so that I can identify what is going wrong. So therefore I need access to fs_cli.

**Comment by plochu** [comment]
> I assume that further configuration needs to be applied that fs_cli can connect.

I have no problem to access fs_cli on my instance...

**Comment by herrep** [comment]
`# service freeswitch status
Redirecting to /bin/systemctl status freeswitch.service
● freeswitch.service - FreeSWITCH
   Loaded: loaded (/usr/lib/systemd/system/freeswitch.service; enabled; vendor preset: disabled)
   Active: active (running) since Fre 2019-06-21 00:56:08 MEST; 16h ago
 Main PID: 15331 (freeswitch)
   CGroup: /system.slice/freeswitch.service
           └─15331 /usr/bin/freeswitch -nc -nf

Jun 21 00:56:08 systemd[1]: Started FreeSWITCH.
Jun 21 00:56:08 freeswitch[15331]: ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
Jun 21 00:56:08 freeswitch[15331]: ERROR: Could not set nice level
`

**Comment by herrep** [comment]
I followed the installation guide at http://ictfax.org/content/ictfax-installation-guide so that I did not any further configuration steps for freeswitch than installing and configuring ICTFAX.

**Comment by herrep** [comment]
Freeswitch as such is running, but fs_cli cannot connect to the socket of freeswitch.

**Comment by plochu** [comment]
@herrep I have just made fresh install using:
1) http://ictfax.org/content/ictfax-installation-guide
2) `yum install ictcore-voice -y`

And I have no problem with VoIP account registration to external provider. Also FreeSwitch CLI (fs_cli) is working without any problem.

**Comment by herrep** [comment]
The server was also configured for IPv6 and freeswitch could not bind to IPv4. However, after re-configuring freeswitch use IPv4, I can connect to fs_cli. Please close issue.

**Comment by kashif-123** [comment]
Hi, 

I am getting the exactly same error while deploying freeswitch through kubernetes. I have my docker image, if I create a container using docker, freeswitch container is successfully created and I am able to make calls normally. However while using the same image, if I create kubernetes deployment and when I go inside freeswitch pod, I am not able to connect to fs_cli and getting same error.

[root@freeswitch-76557dff64-xw2k7 /]# fs_cli
[ERROR] fs_cli.c:1659 main() Error Connecting [Socket Connection Error]
Usage: fs_cli [-H <host>] [-P <port>] [-p <secret>] [-d <level>] [-x command] [-t <timeout_ms>] [profile]

[root@freeswitch-76557dff64-xw2k7 /]# tail -f /var/log/freeswitch/freeswitch.log
2019-10-03 12:39:01.215543 [ERR] sofia.c:3146 Error Creating SIP UA for profile: internal-ipv6 (sip:mod_sofia@[::1]:5060;transport=udp,tcp) ATTEMPT 3 (RETRY IN 5 SEC)
2019-10-03 12:39:01.215543 [ERR] sofia.c:3156 Error Creating SIP UA for profile: internal-ipv6 (sip:mod_sofia@[::1]:5060;transport=udp,tcp)
The likely causes for this are:
1) Another application is already listening on the specified address.
2) The IP the profile is attempting to bind to is not local to this system.
2019-10-03 12:39:01.215543 [ERR] sofia.c:3146 Error Creating SIP UA for profile: external-ipv6 (sip:mod_sofia@[::1]:5080;transport=udp,tcp) ATTEMPT 3 (RETRY IN 5 SEC)
2019-10-03 12:39:01.215543 [ERR] sofia.c:3156 Error Creating SIP UA for profile: external-ipv6 (sip:mod_sofia@[::1]:5080;transport=udp,tcp)
The likely causes for this are:
1) Another application is already listening on the specified address.
2) The IP the profile is attempting to bind to is not local to this system.
^C
[root@freeswitch-76557dff64-xw2k7 /]#

**Comment by gitpel** [comment]
Make sure that the module event socket is loaded
`<load module="mod_event_socket"/>`
in file `/etc/freeswitch/autoload_configs/modules.conf.xml`

**Comment by gitpel** [comment]
make sure that the module `mod_event_socket.so` exist and enabled in the file `/etc/freeswitch/autoload_configs/modules.conf.xml` the line `<load module="mod_event_socket"/>`
to install the module: `apt install freeswitch-mod-event-socket`

**Comment by harshita19012** [comment]
> The server was also configured for IPv6 and freeswitch could not bind to IPv4. However, after re-configuring freeswitch use IPv4, I can connect to fs_cli. Please close issue.

How did you configure freeswitch to use IPV4

**Comment by ICTKashif** [comment]
> > The server was also configured for IPv6 and freeswitch could not bind to IPv4. However, after re-configuring freeswitch use IPv4, I can connect to fs_cli. Please close issue.
> 
> How did you configure freeswitch to use IPV4

https://github.com/ictinnovations/ictfax/issues/46#issuecomment-692472584

edit this file /etc/freeswitch/autoload_configs/event_socket.conf.xml and change listen-ip with 127.0.0.1 and then restart the freeswitch, if still unable to enter fs_cli then and also edit this file /usr/lib/systemd/system/freeswitch.service and change User with root like User=root

restart the freeswitch by `systemctl daemon-reload` and `service freeswitch restart`

**Comment by harshita19012** [comment]
Thanks for your help. Actually I am facing with one more issue of not able to restart freeswitch.

On using systemctl damon-reload I get an error "unknown operation". Is there some other way I can restart freeswitch

**Comment by harshita19012** [comment]
> > > The server was also configured for IPv6 and freeswitch could not bind to IPv4. However, after re-configuring freeswitch use IPv4, I can connect to fs_cli. Please close issue.
> > 
> > 
> > How did you configure freeswitch to use IPV4
> 
> [#46 (comment)](https://github.com/ictinnovations/ictfax/issues/46#issuecomment-692472584)
> 
> edit this file `/etc/freeswitch/autoload_configs/event_socket.conf.xml` and change listen-ip with 127.0.0.1 and then restart the freeswitch, if still unable to enter fs_cli then and also edit this file `/usr/lib/systemd/system/freeswitch.service` and change User with root like User=root
> 
> restart the freeswitch by `systemctl daemon-reload` and `service freeswitch restart`

Thanks for your help. Actually I am facing one more issue of not able to restart freeswitch.

On using systemctl daemon-reload I get an error "unknown operation". Is there some other way I can restart freeswitch

**Comment by harshita19012** [comment]
> > > > The server was also configured for IPv6 and freeswitch could not bind to IPv4. However, after re-configuring freeswitch use IPv4, I can connect to fs_cli. Please close issue.
> > > 
> > > 
> > > How did you configure freeswitch to use IPV4
> > 
> > 
> > [#46 (comment)](https://github.com/ictinnovations/ictfax/issues/46#issuecomment-692472584)
> > edit this file `/etc/freeswitch/autoload_configs/event_socket.conf.xml` and change listen-ip with 127.0.0.1 and then restart the freeswitch, if still unable to enter fs_cli then and also edit this file `/usr/lib/systemd/system/freeswitch.service` and change User with root like User=root
> > restart the freeswitch by `systemctl daemon-reload` and `service freeswitch restart`
> 
> Thanks for your help. Actually I am facing one more issue of not able to restart freeswitch.
> 
> On using systemctl daemon-reload I get an error "unknown operation". Is there some other way I can restart freeswitch

And Service freeswitch restart gives me "freeswitch: unrecognized service "
Actually, when I run freeswitch I get the following error:

2020-09-24 11:25:55.547058 [ERR] sofia.c:3235 Error Creating SIP UA for profile: external (sip:mod_sofia@103.25.231.107:5080;maddr=172.17.0.1;transport=udp,tcp) ATTEMPT 2 (RETRY IN 5 SEC)                                                     2020-09-24 11:25:55.547058 [ERR] sofia.c:3235 Error Creating SIP UA for profile: internal (sip:mod_sofia@103.25.231.107:5060;maddr=172.17.0.1;transport=udp,tcp) ATTEMPT 2 (RETRY IN 5 SEC)                                                     2020-09-24 11:26:00.547058 [ERR] sofia.c:3235 Error Creating SIP UA for profile: external (sip:mod_sofia@103.25.231.107:5080;maddr=172.17.0.1;transport=udp,tcp) ATTEMPT 3 (RETRY IN 5 SEC)                                                     2020-09-24 11:26:00.547058 [ERR] sofia.c:3245 Error Creating SIP UA for profile: external (sip:mod_sofia@103.25.231.107:5080;maddr=172.17.0.1;transport=udp,tcp)                                                                                The likely causes for this are:                                                                                         1) Another application is already listening on the specified address.                                                   2) The IP the profile is attempting to bind to is not local to this system.                                             2020-09-24 11:26:00.547058 [ERR] sofia.c:3235 Error Creating SIP UA for profile: internal (sip:mod_sofia@103.25.231.107:5060;maddr=172.17.0.1;transport=udp,tcp) ATTEMPT 3 (RETRY IN 5 SEC)                                                     2020-09-24 11:26:00.547058 [ERR] sofia.c:3245 Error Creating SIP UA for profile: internal (sip:mod_sofia@103.25.231.107:5060;maddr=172.17.0.1;transport=udp,tcp)                                                                                The likely causes for this are:                                                                                         1) Another application is already listening on the specified address.                                                   2) The IP the profile is attempting to bind to is not local to this system

I thought this is happening because of the IPv6 configuration. I am using freeswitch on a server machine in a docker container. If someone could me regarding this

**Comment by ICTKashif** [comment]
please share your system ssh access informaton at https://service.ictinnovations.com/submitticket.php we will check and let you know

**Comment by ezhevak** [comment]
> The server was also configured for IPv6 and freeswitch could not bind to IPv4. However, after re-configuring freeswitch use IPv4, I can connect to fs_cli. Please close issue.

Please tell us in more detail what exactly did you do?

**Comment by kmpeterson** [comment]
> > The server was also configured for IPv6 and freeswitch could not bind to IPv4. However, after re-configuring freeswitch use IPv4, I can connect to fs_cli. Please close issue.
> 
> Please tell us in more detail what exactly did you do?

I ran into the same issue.  I also had this problem with Asterisk a few years ago; the lesson seems to be "configure for IPv4 first, then deal with IPv6".  I was able to get `fs_cli` to connect by changing `autoload_configs/event_socket.conf.xml` parameter listen-ip from `"::"` to `"127.0.0.1"`.  Hope that helps.

**Comment by iamtalhaasghar** [comment]
for anyone reading this in future you need to make sure 127.0.0.1 is allowed in acl conf as mentioned [here](https://stackoverflow.com/questions/31364064/freeswitch-acl-configuration-for-remote-event-socket)
