### ISSUE TITLE
Email2fax issues

### ISSUE THREAD

**Issue by ugur-demirci** [ictinnovations/ictfax#25]
Hi, 
I need some help. 
ictfax installed on vmware.

sip server          : 192.168.11.4
mail server        : 192.168.11.20 (mail.ugur.com) 
my mail adress : ugur@different_mail_server.com (mails coming this adress)
ictfax                 : 192.168.11.5

When i try to send fax from fax machine to ictfax, i received 3 mail. 
Fist one came from 8211@ugur.com and it says "we have received a request .... )

Second one came from  8211@ugur.com and it says "we have tried to send your fax ... Error: fax transmission:error:data"

Third one came from 8211@**localhost.localdomain** "you have received a fax ... " and my fax pdf is in there. 

Also;
cat try.txt | sendmail ugur@ugur.com 
I received mail from root@**localhost.localdomain** 

I added "smtp" in provider list. "smtp - faks@ugur.com - mail.ugur.com - 587/25" 

Where is the problem ?

**Comment by stan0ne** [comment]
sorunu çözebildinmi hocam?

**Comment by ugur-demirci** [comment]
> sorunu çözebildinmi hocam?

Maalesef hocam. Çok uğraştım ama olmadı...
