### ISSUE TITLE
Email to Fax outbound not working

### ISSUE THREAD

**Issue by dogatemycomputer** [ictinnovations/ictfax#26]
I followed the installation instructions line by line.  I have no problems with any part of the process.

When sending a fax from my email address to the server I receive the following errors:

> [2019-08-04 19:34:01] [31454] [FLOW] =================> processing response <=================
> [2019-08-04 19:34:01] [31454] [FLOW] Processing status of application : email_receive
> [2019-08-04 19:34:01] [31454] [FLOW] No transmission found, searching for dialplan
> [2019-08-04 19:34:01] [31454] [INFO] looking for available dialplan
> [2019-08-04 19:34:01] [31454] [FLOW] Trying with dialplan id : 1
> [2019-08-04 19:34:01] [31454] [ERROR] Request: ICT\Core\Request Object
> (
>     [gateway_flag] => 4
>     [context] => internal
>     [spool_id] => 
>     [application_id] => email_receive
>     [application_data] => Array
>         (
>             [subject] => Test
>             [body] => 
>             [body_alt] => 
>             [attachment] => /usr/ictcore/cache/ictcore_fe48FXPriceList.pdf
>             [status] => completed
>             [response] => 
>             [result] => success
>         )
> 
>     [source] => dave@testcompany.com
>     [destination] => 1234567890@fax101.testcompany.com
> )
> 
> [2019-08-04 19:34:01] [31454] [ERROR] No recipient found
> [2019-08-04 19:34:01] [31454] [ERROR] Unable to locate appropriate dialplan
> [2019-08-04 19:34:01] [31454] [WARNING] Skipping current email: Unable to locate appropriate dialplan

I created a user named "dave@testcompany.com".  The login is "dave@testcompany.com" and the email in the "User address" section of the profile uses the same email address.  

This is the contents of my dialplan table:

> MariaDB [(none)]> select * from ictfax.dialplan;
> +-------------+--------------+--------+-------------+----------+--------+------------+----------------+-------------+
> | dialplan_id | gateway_flag | source | destination | context  | weight | program_id | application_id | filter_flag |
> +-------------+--------------+--------+-------------+----------+--------+------------+----------------+-------------+
> |           1 |            4 | %      | %           | internal |      0 | 1          | email_receive  |          31 |
> +-------------+--------------+--------+-------------+----------+--------+------------+----------------+-------------+
> 1 row in set (0.00 sec)
> 
> MariaDB [(none)]> 
> 

What other information can I provide that may be helpful?

Thank you.

**Comment by ICTKashif** [comment]
Please make sure this email address "dave@testcompany.com" exist in ICTFax database, if email address exist in system then you can use Email2Fax option otherwise you cannot.

So, Please create new account, add email address " dave@testcompany.com " then you can use Email2Fax
