### ISSUE TITLE
Email2fax using Subject for Destination number

### ISSUE THREAD

**Issue by vladutz33** [ictinnovations/ictfax#27]
Hello,
What should I change in the code to use the subject of the email as a destination for email2fax. 
I want to use a single email address as destination and send the number in the subject. Something like mail2fax@provider.com and in the Subject of the mail to insert the number. Could this be done?

**Comment by ICTKashif** [comment]
You can change email templates from following folder 
```
/usr/ictcore/core/Program/Emailtofax/data/
/usr/ictcore/core/Program/Faxtoemail/data/
```

and regarding email address, you can change from ictcore configuration file
`/etc/ictcore.conf`
