### ISSUE TITLE
No cyrillic encoding

### ISSUE THREAD

**Issue by radoslav-stoyanov** [ictinnovations/ictfax#29]
When I upload documents with names in Cyrillic alphabet the system does not recognize it. Screenshot: [https://i.imgur.com/a1SdFUh.png](https://i.imgur.com/a1SdFUh.png)

**Comment by ICTKashif** [comment]
You can only use English Language in ICTFax. if you need this then please create support ticket at https://service.ictinnovations.com/submitticket.php
