### ISSUE TITLE
How to isolate users and DIDs from each other

### ISSUE THREAD

**Issue by syadnom** [ictinnovations/ictfax#30]
I'm testing this out because of it's claimed 'service provider' solution, but I'm having trouble seeing how to isolate users from each other.

It seems that all users can see all DIDs on the system.

**Comment by ICTKashif** [comment]
ICTFax opensource version is not a service provider / multi-tenant software, if you are interested in service provider / multi-tenant edition, Please create a support ticket at https://service.ictinnovations.com/submitticket.php

**Comment by syadnom** [comment]
Please modify the very first line here:
http://ictfax.org/

where it says:
"ICTFAX is a free and open source GNU GPLv3 based multi-user and web based Fax software solution for service providers and businesses. "

to reflect this.  It's currently misleading.

**Comment by ICTKashif** [comment]
ICTFax support multi-user, there is no limit on users

**Comment by syadnom** [comment]
"service providers"

**Comment by tahiralmas** [comment]
Thanks for update, we have modified accordingly  however you can use  REST API's  to fulfill your requirements  also we  are already  working on multi tenant feature and providing customized solution  to interested service providers
