### ISSUE TITLE
timeout on 'processing'

### ISSUE THREAD

**Issue by syadnom** [ictinnovations/ictfax#31]
I've done some test faxes to my cell phone.  I get a call and a beep, but when I hang up it never seems to fail that fax.  Where is this configurable?

If I do the same and put retries at 3, the first attempt never seems to complete and so the retries never happen.

**Comment by ICTKashif** [comment]
Regarding Retires option, We have forwarded this issue to our development team. We will fix it in next version of ICTFax.

For failed faxes, Please check call logs from FreeSwitch CLI.

**Comment by syadnom** [comment]
I haven't seen any that were failed erroneously.  It's just the ones stuck on 'processing' that never fail or retry etc.

**Comment by ICTKashif** [comment]
Please also check ICTCore and Apache log

```
/var/log/httpd/error_log
/usr/ictcore/log/ictcore.log
```
