### ISSUE TITLE
Regex (FAIL) destination_number

### ISSUE THREAD

**Issue by operaciones1** [ictinnovations/ictfax#36]
When a fax arrives at ictfax, we have a regex error ->
Regex (FAIL) [application_input] destination_number (provider username) = ~ / ^ \ +? (\ D +) $ /

and consequently we have NO_ROUTE_DESTINATION

I have sought help to configure the SIP provider and indicate the destination, but I have not found anything

**Comment by fizaict** [comment]
Actually the issue is here because you are using provider username so it is giving Regex error because it accepts only digits. Infact instead of provider username you should use extension number or did number and that should be in digits no alphanumeric are accepted
