### ISSUE TITLE
Install Issue on executing "./email_to_fax"

### ISSUE THREAD

**Issue by marc-amlung** [ictinnovations/ictfax#38]
Hello,

I have a problem by completing the install process on the step, where I have to execute
the ./email_to_fax file.
It replys the following error:

`PHP Fatal error:  Can't use function return value in write context in /usr/ictcore/core/Program/Emailtofax.php on line 205`

I have tried to use the Software anyway but Email2Fax is not working.
Sending fax via Webinterface is working.

Hope you can help.

Thanks.

**Comment by fizaict** [comment]
This issue is fixed. Kindly update your installation.
