### ISSUE TITLE
only T38 faxes but T30 (g711)needed

### ISSUE THREAD

**Issue by mbike2000ru** [ictinnovations/ictfax#4]
During FAX OUT - t38 fax was initiated
But T30 (g711) is needed

**Comment by tahiralmas** [comment]
if you are using latest version you need remove t38 related parameters ( lines ) 

please edit anyone of the following ( depending on your version )

/usr/ictcore/core/templates/application/fax_send/freeswitch/default.json
or
/usr/ictcore/core/Gateway/Freeswitch/templates/application/fax_send.json
