### ISSUE TITLE
Inbound Faxes Do Not Show Up In My Inbox

### ISSUE THREAD

**Issue by samsantiago89** [ictinnovations/ictfax#41]
Hello,

I am hoping someone might be able to help me with the issue that I am running into. I am currently able to send faxes without any issues. When I call my fax number I get a fax tone. If I fax into myself I get a confirmation that my fax was received but they don't show up in my inbox or in the administrators inbox. I have walked through the steps outlined in the installation guide with no luck.

Is there anyways you might be able to tell me if I need to configure something further in Freeswitch or is this all done using the Web Interface? If I need to configure Freeswitch to write the .tif image I can do that just need to know where I should have those dropped in order for them to appear in the inbox or do the images write to the database?

I think if I understood where the image are pulled from in order for them to show correctly in the inbox it would help.

 I am super sure that this is going to be a super simple fix just need to get a better understanding why ICTFAX works. Were are all the images for outbound faxes stored as well as inbound faxes. So if I wanted to delete fax images to avoid my hard drive building up what is the best process for this?

I also checked the ICTCore Log : /usr/ictcore/log/ictcore.log and dont see anything in there for the inbound test call send today. On my end I get a confirmation that my fax was received and in the fs_cli I see that call transaction. Let me know if there is any logs I can capture for review. 

Thank you,

**Comment by ntnher** [comment]
Hi Samsantiago89. 

I hope I warn others from spending too much time on this. This is a known issue.

I had the same issue you have here. I ran into a dead end with this. In the previous version I was able to receive email notification when I received a fax. With this new version, it looks like email is broken. I opened a ticket with the commercial people at ICTfax. They told me to reinstall a clean copy and I did this multiple times. Each time with the same results, no email notifications when fax is received. They were trying too look at my ticket and they asked to access my CentOS. I gave them access and nothing happened for two weeks, then all the sudden my ticket disappeared. I could not access the link to the ticket. My installation never worked like the website describes, no emails. On the website there is $300 install service, install script sign up (I heard others paid for the script), and enterprise solution services. I'm guessing that they want to be paid. I work in IT and I'm testing this for a prove of concept for my company, but it's a fail. I would gladly pay for the installation service, if the community edition works.

Here is something you may want to try out, www.srfax.com. The basic subscription does not get you our own domain, but it works and it's very inexpensive. You pay about the same amount for a DID number already, why not get email to fax on a DID for the same price. I'm looking to do DNS reroute to direct emails from my work domain to SRfax.

**Comment by fizaict** [comment]
Hy Samsantiago89!

There are a number of installations in production every month. Customers are using it successfully. Can you please tell out that which version of ictcore you are currently using? Please tell it our so that we can help you in fixing the issue?
