### ISSUE TITLE
default credentials not working

### ISSUE THREAD

**Issue by chaima1995** [ictinnovations/ictfax#44]
The default credentials mentioned on the installation guide are not working, can you tell me the updated credentials?
![1](https://user-images.githubusercontent.com/67378435/85573777-1842c000-b62e-11ea-8b17-2211047e00dd.PNG)
![2](https://user-images.githubusercontent.com/67378435/85573852-27297280-b62e-11ea-90ba-f1e3221ce839.PNG)

**Comment by fizaict** [comment]
Have you installed the ICTFax or checking the demo site?

**Comment by chaima1995** [comment]
> Have you installed the ICTFax or checking the demo site?

Thank you for replying, I have installed it

**Comment by chaima1995** [comment]
> Ok @chaima1995 can you please tell which version of ICTCore, you have installed?

![00944357-5486-4230-87EB-4A5BEA8D9ADF](https://user-images.githubusercontent.com/67378435/85670532-e4f94300-b6b8-11ea-9385-58e50a79ec0c.jpeg)
I installed it yesterday using the command attached, so I don’t have an idea about the version. I will be in the office in a bit so I will be able to check if you have a command that tells the version 
Thank you :)

**Comment by fizaict** [comment]
Can you please share ICTCore logs so I can have a better idea of why it is not running?

**Comment by chaima1995** [comment]
> 
> 
> Can you please share ICTCore logs so I can have a better idea of why it is not running?

Sorry for the late reponse.

This is the error I got yesterday 
![ictcore log](https://user-images.githubusercontent.com/67378435/85735807-e39a3b80-b6f5-11ea-9e40-59b44145ee1b.PNG)

and this si the DB conf I made using the installation guide
![ictcore conf](https://user-images.githubusercontent.com/67378435/85735906-f57bde80-b6f5-11ea-8a03-6be372154dd3.PNG)

**Comment by fizaict** [comment]
It seems like there is an issue with your database setup. I think you must have skipped some points during installation. That's why you are facing an issue now.

**Comment by fizaict** [comment]
Were you able to fix the issue? Update please so that we can help you

**Comment by chaima1995** [comment]
> 
> 
> It seems like there is an issue with your database setup. I think you must have skipped some points during installation. That's why you are facing an issue now.

Hello,
Sorry for the delay, I had to deal with other projects
I actually didn't skip the steps but I will see what I can do and I'll keep you updated

**Comment by fizaict** [comment]
ok sure

**Comment by chaima1995** [comment]
> 
> 
> ok sure

Good morning,

The issue is soved. Thank you :)

**Comment by fizaict** [comment]
Great!

**Comment by ptphillips** [comment]
Good evening,

Hope you are well.

What was the fix? I followed the install guide, including the database setup portion, and the credentials are not working for me either.

Here's the installed version.

ictcore.noarch                            1.0.3.17deead-main.el7     @ict
ictcore-email.noarch                      1.0.3.17deead-main.el7     @ict
ictcore-fax.noarch                        1.0.3.17deead-main.el7     @ict
ictcore-freeswitch.noarch                 1.0.3.17deead-main.el7     @ict
ictcore-kannel.noarch                     1.0.3.17deead-main.el7     @ict
ictcore-sendmail.noarch                   1.0.3.17deead-main.el7     @ict
ictcore-sms.noarch                        1.0.3.17deead-main.el7     @ict
ictcore-voice.noarch                      1.0.3.17deead-main.el7     @ict
ictfax.noarch                             4.3.0.3-beta.el7           @ict
kannel.x86_64                             1.4.4-1cnt7                @ict
php-pecl-libevent.x86_64                  0.1.0-2.el7.centos         @ict

Where are the ICTCore logs?

Any guidance would be appreciated.

Cheers!
Patrick
