### ISSUE TITLE
File field.info.class.inc is missing

### ISSUE THREAD

**Issue by albocc** [ictinnovations/ictfax#6]
When attempting to follow the [installation guide](http://ictfax.org/content/ictfax-20-installation-guide), I noticed an error in Drupal, where a required file was not found: `file.info.class.inc` in `modules/field/`.

After searching for the file online, I found the source [here](https://api.drupal.org/api/drupal/modules%21field%21field.info.class.inc/7.x) and copied that file into my installation which enabled me to complete the setup.

**Comment by tahiralmas** [comment]
probably you mean field.info.class.inc ? It is fixed as per your report
Thanks
