### ISSUE TITLE
user login will logout after one second

### ISSUE THREAD

**Issue by tronerbe1977** [ictinnovations/ictfax#63]
helo
i added user with all parameters
but when i want to login after iam logged in successfully, i will automaticly logout from the webinterface
its only possible with the admin@ictcore.org  user

what i do wrong?

thanks

**Comment by beeeecky223** [comment]
Hey, I also got this problem.
When I create an new user with Admin + User roles, he can login successfully;
but when I create an new user with only User role, he login then immediately logout after one second (means cannot do cannot thing).
Any solutions for this problem? I cannot create users who are all having Admin roles....

**Comment by ICTKashif** [comment]
In the Community Edition, you must select both roles for new users. Additionally, for multi-tenancy, you need to select Service Provider Edition.

**Comment by smule98** [comment]
> In the Community Edition, you must select both roles for new users. Additionally, for multi-tenancy, you need to select Service Provider Edition.

For me doesn't works this solution.
Immediately logout also with double permissions
