### ISSUE TITLE
DB error in apache

### ISSUE THREAD

**Issue by bsher-osi** [ictinnovations/ictfax#66]
Used the centos7 installation script as well as the manual install and keep getting the same apache error.

[Sun Oct 31 16:23:45.119744 2021] [:error] [pid 20082] [client 70.162.111.146:61608] PHP Fatal error:  Class 'ICT\\Core\\ICT\\Core\\Conf\\User' not found in /usr/ictcore/core/lib/common.php on line 132, referer:

Any tips to resolve?

**Comment by fizaict** [comment]
Go to file `/usr/ictcore/core/lib/common.php` and change the line 32 as follows:

    Conf\User::load();
