### ISSUE TITLE
Problem with ictinnovation repository

### ISSUE THREAD

**Issue by mj82** [ictinnovations/ictfax#7]
Hello,

I am trying to install ictfax on centos 6. I receive the following error when trying to add ictinnovation repository with command rpm -Uvh 'http://service.ictinnovations.com/repo/6/ict-release-6-2.noarch.rpm'

Retrieving http://service.ictinnovations.com/repo/6/ict-release-6-2.noarch.rpm
error: /var/tmp/rpm-tmp.T9d13p: not an rpm package (or package manifest):

On a centos 7 server the https://service.ictinnovations.com/repo/7/ict-release-7-4.el7.centos.noarch.rpm gives me a 404 - Not Found error.

How can I install ictinnovations repos?

Thanks

**Comment by tahiralmas** [comment]
Sorry for the inconvenience, It was down due to maintenance. Now it up and running.
Enjoy !
