### ISSUE TITLE
dashboard not working

### ISSUE THREAD

**Issue by kmorber** [ictinnovations/ictfax#89]
Hi,

the dashboard is not working for me, just a blue site shows but nothing goes any further.

![2024-04-09 20 44 28](https://github.com/ictinnovations/ictfax/assets/1584056/d8f411ec-b296-498a-a875-360c0869f025)

What can i do?

**Comment by ictvision** [comment]
Please check the apache and ictcore logs `tail -n50 /usr/ictcore/log/ictcore.log` and share here

**Comment by kmorber** [comment]
[access_log.txt](https://github.com/ictinnovations/ictfax/files/15075972/access_log.txt)
[error_log.txt](https://github.com/ictinnovations/ictfax/files/15075973/error_log.txt)
[ictcore.log](https://github.com/ictinnovations/ictfax/files/15075974/ictcore.log)

filles attached
