### ISSUE TITLE
settings.php writable detection bug in install.core.inc

### ISSUE THREAD

**Issue by acrawly** [ictinnovations/ictfax#9]
We're really not sure if this is a bug or our misunderstanding. Either way. When looking at line 1701 in install.core.inc, there is this code:

    $writable = drupal_verify_install_file($settings_file, FILE_READABLE|FILE_WRITABLE);
    = false

Which for us was returning false everytime. We knew 100% that the file was indeed writable. So adjusting the code to this these options worked:

    $writable = drupal_verify_install_file($settings_file, FILE_READABLE||FILE_WRITABLE);
    =true
    $writable = drupal_verify_install_file($settings_file, FILE_READABLE&&FILE_WRITABLE);
    =true

So we adjusted the code and continued our install. No issues. 

I also looked at the source code of `drupal_verify_install_file()` which appears to be expecting an array for the mask. Is `FILE_READABLE|FILE_WRITABLE` shorthand for an array? If not, maybe that is the issue?

Anyways just wanted to point this out in case this is truly a bug or limited to our environment.

**Comment by tahiralmas** [comment]
First of all please note that we use drupal as base framework for ICTFax application. so you can search / get help from Drupal community as well. 

However there is no such reported error in Drupal as you mentioned, probably Apache user need permission on setting file. Or selinux no disabled. If you have experience with Linux you can easily fix this issue.

    setenforce 0
